#!/usr/bin/env python3
"""Generate a single-header amalgamation of arbitro-c (stb-style).

Usage:
    python scripts/amalgamate.py > dist/arbitro_single.h

To use in your project:
    #define ARBITRO_IMPLEMENTATION
    #include "arbitro_single.h"
"""

import os
import re
import sys

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(SCRIPT_DIR)
HEADER = os.path.join(ROOT, "include", "arbitro", "arbitro.h")
SOURCE = os.path.join(ROOT, "src", "arbitro.c")


def read_file(path):
    with open(path, "r", encoding="utf-8") as f:
        return f.read()


def strip_self_include(source):
    return re.sub(
        r'^\s*#include\s+"arbitro/arbitro\.h"\s*$',
        "",
        source,
        flags=re.MULTILINE,
    )


def main():
    header = read_file(HEADER)
    source = read_file(SOURCE)

    source = strip_self_include(source)

    out = []
    out.append("/*")
    out.append(" * arbitro_single.h -- single-header amalgamation of arbitro-c")
    out.append(" *")
    out.append(" * Define ARBITRO_IMPLEMENTATION in exactly ONE .c file before including.")
    out.append(" *")
    out.append(" * Generated by scripts/amalgamate.py -- do not edit by hand.")
    out.append(" */")
    out.append("")
    # glibc latches its feature-test macros the first time any system header
    # is seen. The public header includes <stdint.h>, so the macro src/arbitro.c
    # sets for clock_gettime arrives too late here and a -std=c99 consumer
    # fails to build. Emit it before anything else is included.
    out.append("#ifndef _WIN32")
    out.append("#  ifndef _POSIX_C_SOURCE")
    out.append("#    define _POSIX_C_SOURCE 200112L")
    out.append("#  endif")
    out.append("#endif")
    out.append("")
    out.append(header)
    out.append("")
    out.append("#ifdef ARBITRO_IMPLEMENTATION")
    out.append("")
    out.append(source)
    out.append("")
    out.append("#endif /* ARBITRO_IMPLEMENTATION */")
    out.append("")

    sys.stdout.reconfigure(encoding="utf-8")
    print("\n".join(out))


if __name__ == "__main__":
    main()
